name: IAST
on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened]
jobs:
  run-tests:
    name: ZAP Scan
    permissions: write-all
    runs-on: self-hosted
    steps:
      - name: Checkout the repo
        uses: actions/checkout@v3
      
      # - name: Create zapnet
      #   run: docker network create zapnet

      - name: Bulding container
        run: docker build -t my-apache2 .

      - name: run docker
        run: docker run -p 80:80 --name docker-apache -d --net bridge my-apache2

      - name: check directory
        run: docker exec docker-apache cat /etc/hosts

      # - name: check server
      #   run: curl http://172.17.0.2
        
      - name: check dps
        run: docker ps

      - name: check network
        run: docker network ls

      - name: docker inspect
        run: docker inspect docker-apache | grep IPAddress

      # - name: ZAP
      #   run: docker run --net zapnet -v $(pwd):/zap/wrk/:rw -t ghcr.io/zaproxy/zaproxy:stable zap-full-scan.py -t http://172.18.0.2 -J report_json.json -w report_md.md -r report_html.html

      - name: ZAP Scan
        uses: hermanka/action-full-scan@master 
        with:
          target: 'http://172.17.0.2'
          # cmd_options: '; curl 172.18.0.2'
      
      - name: stop docker
        run: docker stop docker-apache
     
